# AUTOGENERATED FILE - DO NOT MODIFY!
# This file was generated by Djinni from using_custom_datatypes.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyRecord, CPyString
from _cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

from custom_datatype import CustomDatatype

class CustomDatatypeHelper:
    @staticmethod
    def release(c_ptr):
        assert c_ptr in c_data_set
        c_data_set.remove(ffi.cast("void*", c_ptr))

    @ffi.callback("struct DjinniString *(struct DjinniRecordHandle *)")
    def get_custom_datatype_f1(cself):
        try:
            with CPyString.fromPy(CPyRecord.toPy(None, cself).recordData) as py_obj:
                _ret = py_obj.release_djinni_string()
                assert _ret != ffi.NULL
                return _ret
        except Exception as _djinni_py_e:
            CPyException.setExceptionFromPy(_djinni_py_e)
            return ffi.NULL

    @ffi.callback("struct DjinniRecordHandle *(struct DjinniString *)")
    def python_create_custom_datatype(recordData):
        py_rec = CustomDatatype(
            CPyString.toPy(recordData))
        return CPyRecord.fromPy(CustomDatatype.c_data_set, py_rec) #to do: can be optional?

    @ffi.callback("void (struct DjinniRecordHandle *)")
    def __delete(dh):
        assert dh in CustomDatatype.c_data_set
        CustomDatatype.c_data_set.remove(dh)

    @staticmethod
    def _add_callbacks():
        lib.custom_datatype_add_callback_get_custom_datatype_f1(CustomDatatypeHelper.get_custom_datatype_f1)
        lib.custom_datatype_add_callback___delete(CustomDatatypeHelper.__delete)
        lib.custom_datatype_add_callback_python_create_custom_datatype(CustomDatatypeHelper.python_create_custom_datatype)

CustomDatatypeHelper._add_callbacks()

